excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  
  
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 185

disabled_rules: # rule identifiers to exclude from running
  - variable_name